---
timezone: Europe/Berlin
ssh_port: 22
pihole_password: foofoo

rumble__base_url: https://console.rumble.run/download/explorer
rumble_token: "<YOUR_TOKEN>"
rumble_arch: "linux-arm64"
rumble_build: "628110af"
