---

# ~*~*~*~*~*~*~*~*~*~*~*~ Setup hostname ~*~*~*~*~*~*~*~*~*~*~*~
- name: Write hostname to /etc/hostname
  ansible.builtin.copy:
    content: "{{ hostname }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Issue hostname command
  ansible.builtin.hostname: name={{ hostname }}

- name: Add hostname entries to hosts file (localhost)
  ansible.builtin.lineinfile: dest=/etc/hosts regexp="^127.0.0.1" line="127.0.0.1 localhost {{ hostname }}" state=present

# ~*~*~*~*~*~*~*~*~*~*~*~ Setup timezone ~*~*~*~*~*~*~*~*~*~*~*~
- name: Set timezone
  ansible.builtin.copy:
    content: '{{ timezone }}'
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644

- name: Remove existing localtime configuration file
  ansible.builtin.file:
    path: /etc/localtime
    state: absent

- name: Set localtime to UTC
  ansible.builtin.file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link
    owner: root
    group: root
    mode: 0644

- name: Reconfigure tzdata
  ansible.builtin.command: dpkg-reconfigure -f noninteractive tzdata
  changed_when: true

# ~*~*~*~*~*~*~*~*~*~*~*~ Setup ufw ~*~*~*~*~*~*~*~*~*~*~*~
- name: Install ufw
  ansible.builtin.apt:
    package: ufw
    state: present
  notify: restart server

- name: Configure ufw defaults
  ansible.builtin.ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - {direction: 'incoming', policy: 'deny'}
    - {direction: 'outgoing', policy: 'allow'}
  notify:
    - restart ufw

- name: Configure ufw rules
  ansible.builtin.ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - {rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp'}
    - {rule: 'allow', port: '80', proto: 'tcp'}
    - {rule: 'allow', port: '443', proto: 'tcp'}
  notify:
    - restart ufw

- name: Enable ufw logging
  ansible.builtin.ufw: logging=on
  notify:
    - restart ufw

- name: Enable ufw
  ansible.builtin.ufw: state=enabled
