---
- name: Download executable from rumble
  ansible.builtin.get_url:
    url: "{{ rumble__base_url }}/{{ rumble_token }}/{{ rumble_build }}//rumble-explorer-{{ rumble_arch }}.bin"
    dest: /tmp/rumble-explorer.bin
    owner: root
    group: root
    mode: 0755

- name: Install rumble-explorer
  ansible.builtin.command: /tmp/rumble-explorer.bin
  changed_when: true

- name: Remove install file
  ansible.builtin.file:
    path: /tmp/rumble-explorer.bin
    state: absent
